### ISSUE TITLE
How to evaluate the results?

### ISSUE THREAD

**Issue by Starboy-at-earth** [MinghanLi/STMask#2]

**Comment by Starboy-at-earth** [comment]
It seems that the only output is a .json file.

**Comment by Starboy-at-earth** [comment]
The server reminds me that the generated json file is "Invalid file type (application/json)".

**Comment by Starboy-at-earth** [comment]
@MinghanLi

**Comment by MinghanLi** [comment]
> The server reminds me that the generated json file is "Invalid file type (application/json)".
The .json file is used to evaluate YTVIS2019 validation results in the [Codelab](https://competitions.codalab.org/competitions/20128#participate-submit_results) . If you want to show segmentation results of frames, just add '--display'.

If your problem still not is solved, can you list detailed error information about "Invalid file type (application/json)"？

**Comment by Starboy-at-earth** [comment]
> > The server reminds me that the generated json file is "Invalid file type (application/json)".
> > The .json file is used to evaluate YTVIS2019 validation results in the [Codelab](https://competitions.codalab.org/competitions/20128#participate-submit_results) . If you want to show segmentation results of frames, just add '--display'.
> 
> If your problem still not is solved, can you list detailed error information about "Invalid file type (application/json)"？

I  have solved it. I renamed the .json file as results.json, and compressed it with the zip protocol. Thank you very much!!!
