### ISSUE TITLE
Error from Youtube 2019 Evaluation

### ISSUE THREAD

**Issue by Meryl-Fang** [MinghanLi/STMask#4]
Thank you for sharing the repo!

We are trying to reproduce the results of Youtube2019 based on your instructions. We tried two different pretrained weights, but got the same errors:

`RuntimeError: invalid spatial size of offset, expected height: %d width: %d, but got height: %d width: %d50784880 (deform_conv_shape_check at ./mmcv/ops/csrc/pytorch/deform_conv_cuda.cu:177)`

The two commands we used were as follows:
`python eval.py --config=STMask_plus_base_ali_config --trained_model=weights/STMask_plus_base_ali.pth --mask_det_file=weights/results.json`

`python eval.py --config=STMask_plus_base_ada_config --trained_model=weights/STMask_plus_base_ada.pth --mask_det_file=weights/results.json`

We would really appreciate some help, thank you very much!

**Comment by PanXiongAdam** [comment]
Hi，I have the same problem. Are you solved it? if solved it, can you tell me how to solve it please? thank you very much

**Comment by MinghanLi** [comment]
FCB(ali) and FCB(ada) use deformable convolutions with different height and width (like 3*5). But there are some error in mmcv/ops/deform_conv.py to support deformable convolutions with different height and width. You have to replace padW=ctx.padding[1], padH=ctx.padding[0] with padW=ctx.padding[0], padH=ctx.padding[1] in mmcv/ops/deform_conv.py by yourself.

Taking Line 81-89 as an example:
    ```Shell
    ext_module.deform_conv_forward(
            input,
            weight,
            offset,
            output,
            ctx.bufs_[0],
            ctx.bufs_[1],
            kW=weight.size(3),
            kH=weight.size(2),
            dW=ctx.stride[1],
            dH=ctx.stride[0],
            padW=ctx.padding[0],
            padH=ctx.padding[1],
            dilationW=ctx.dilation[1],
            dilationH=ctx.dilation[0],
            group=ctx.groups,
            deformable_group=ctx.deform_groups,
            im2col_step=cur_im2col_step)
    ```

**Comment by Meryl-Fang** [comment]
for future reference, there are two spots to change: line 84-85, and line 120-121 :D

**Comment by qihao-huang** [comment]
> for future reference, there are two spots to change: line 84-85, and line 120-121 :D

as well as line 140-141
