### ISSUE TITLE
Confuse about batchsize and total iterations

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [MinghanLi/STMask#6]
Dear author, thanks for your great job! I'm trying to train STMask and I find the batchsize and max_iter you gave in the code is different from the paper.
In the paper, you set bz 16 and total iters 160000. 

![paper](https://user-images.githubusercontent.com/53077461/128137867-12d99b31-71a3-47c0-b214-28106325e0c1.PNG)

But in the code you set bz 8 and max_iters 250000
![bzreal](https://user-images.githubusercontent.com/53077461/128137887-bce3adaf-a245-486f-a4f4-fd1c41bb445d.PNG)
![iters](https://user-images.githubusercontent.com/53077461/128137998-eaaff013-0580-4129-abc8-e374784d8e5a.PNG)

So, I want to know the exact paramters to get the final result.

**Comment by MinghanLi** [comment]
Please set all parameters according to our paper. When updating the code, I forgot to set them as default.

**Comment by EDENpraseHAZARD** [comment]
Waht about the numbers of 2080Ti you used for training.
Thanks a lot.

**Comment by EDENpraseHAZARD** [comment]
What about the numbers of 2080Ti you used for training?
Thanks a lot.

**Comment by MinghanLi** [comment]
@EDENpraseHAZARD We trained all models on 4 2080Ti GPUS in total, 4 paired images  for each 2080Ti.
